apiVersion: v1
data:
  com.enonic.xp.cluster.cfg: |-
    cluster.enabled = true
    network.host = _eth0_
    network.publish.host = _eth0_
  com.enonic.xp.elasticsearch.cfg: |
    node.data = true
    node.master = true

    discovery.unicast.sockets = {{ .Release.Name }}-intra-service.{{ .Release.Namespace }}.svc.cluster.local

  {{- with .Values.customESConfigs }}
    {{ . | nindent 4 }}
  {{- end }}  

  com.enonic.xp.hazelcast.cfg: |
    clusterConfigDefaults = false

    network.join.kubernetes.enabled = true

    network.join.kubernetes.serviceDns = {{ .Release.Name }}-intra-service.{{ .Release.Namespace }}.svc.cluster.local

    network.join.tcpIp.enabled = false

    network.restApi.enabled = true

    # Initial expected cluster size to wait before node to start completely
    system.hazelcast.initial.min.cluster.size = 1
  com.enonic.xp.web.sessionstore.cfg: |-
    #replicated or non-persistent
    storeMode = replicated

    # Controls whether a session that is newly created will be immediately (true)
    # or lazily (false) persisted as the last request for the session exits.
    # Has no effect in non-persistent storeMode.
    saveOnCreate = true

    # Controls whether a session that is changed ("dirty") will be persisted as the response is about to commit.
    # If false, a dirty session will only be persisted when the last simultaneous request for it leaves the session.
    # Has no effect in non-persistent storeMode.
    flushOnResponseCommit = true
  system.properties: |-
    xp.suPassword = {{ .Values.suPassword }}
    xp.init.adminUserCreation = false

  com.enonic.xp.web.vhost.cfg: |-
{{ indent 4 .Values.vhosts }}

{{- with .Values.customEnonicConfigs | default dict }}
{{ toYaml . | nindent 2 }}
{{- end }}

  logback.xml: |-
    <?xml version="1.0"?>
    <configuration scan="true" scanPeriod="60 seconds">

      <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
          <pattern>{{ .Values.customLoggingFormat }}</pattern>
        </encoder>
      </appender>

      <root level="info">
        <appender-ref ref="STDOUT"/>
      </root>

      <logger name="org.apache.ignite" additivity="false">
        <level value="WARN"/>
        <appender-ref ref="STDOUT"/>
      </logger>

    </configuration>



kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
