# ---------- Ingress entry ------------
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/from-to-www-redirect: {{ .Values.ingress.redirectFromWWW | quote }}
    {{- if .Values.ingress.ssl | default false }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.sslIssuer | quote }}
    {{- end }}
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.maxBodySize }}
    nginx.ingress.kubernetes.io/affinity: "cookie"
spec:
{{- if .Values.ingress.ssl | default false }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        {{- if or (not (hasKey . "ssl")) .ssl }}
        - {{ .host | quote }}
        {{- end }}
        {{- end }}
      secretName: {{ .Release.Name }}-tls
{{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $.Values.appInfo.name }}-service
              servicePort: 8080
    {{- end }}
