{{- $auth := printf "su:%s" .Values.suPassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
  namespace: {{ .Release.Namespace }}
data:
  auth: {{ $auth | b64enc }}
type: Opaque