---
# ---------- Exposer service ------------
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    name: {{ .Release.Name }}
  ports:
  - name:  xp-port
    port:  8080
    targetPort:  8080

---
# ---------- Internal service ------------
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-intra-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    name: {{ .Release.Name }}
  ports:
    - port: 5701
      name: hazelcast
    - port: 9300
      name: elasticsearch
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
