image:
  repository: enonic/xp
  pullPolicy: IfNotPresent
  tag: "7.4.1-ubuntu"

suPassword: changeme

JarSpecs:
  prefix: "sample-project-"
  name: sample-project-1.1.0.jar
  bucketOptions:
    secret: bucket-secret
    url: s3.example.com
    suffix: sample-project/staging

smtp:
  enabled: false
  image: namshi/smtp

envVars: []
#   - name: JAVA_OPTS
#     value: -Xms2G -Xmx2G

probes:
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 2

terminationGracePeriodSeconds: 180

replicaCount: 1

annotations: {}

labels: {}

podAnnotations: {}

podLabels: {}

imagePullSecrets: []

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
    # memory: 2000Mi

nodeSelector: {}

tolerations: []

affinity: {}

volumeSpec:
  storageClass: "managed-nfs-storage"
  sizes:
    blobs: 3Gi
    data: 3Gi
    snapshots: 3Gi
    deploy: 400Mi


ingress:
  sslIssuer: "letsencrypt-prod"
  ssl: true
  redirectFromWWW: true
  maxBodySize: 1000m
  hosts:
    - host: app.example.com
    # - host: localhost
    #   ssl: false

vhosts: |-
  enabled = false

  mapping.site.host = app.example.com
  mapping.site.source = /
  mapping.site.target = /site/default/master/example

  mapping.admin.host = app.example.com
  mapping.admin.source = /admin
  mapping.admin.target = /admin
  mapping.admin.idProvider.system = default

customEnonicConfigs: {}
  # com.enonic.xp.mail.cfg: |-
  #   smtpHost=smtp.gmail.com
  #   smtpPort=587
  #   smtpAuth=true
  #   smtpUser=test@test.com
  #   smtpPassword=password
  #   smtpTLS=true

